"""
    An AI Tool for Student-Supervisor Allocation.
    
    Package: pystsup
    Module: data
    File: supervisor.py
    
    Purpose:  Contains Supervisor class, which structures and holds data of a particular supervisor.
             
    Author : Rithin Chalumuri
    Version: 1.0 
    Date   : 21/7/17
    
"""

class Supervisor:

    def __init__(self,supID,keywords, quota,realID=None,name=None):

        """
        Initialize the Supervisor object.

        Parameters:
        
            supID (string) -  is the internal ID (eg. "supervisor1") given to a supervisor generated by this program,
                              this id is also a key in the supervisor data dictionary.
                              
            keywords (dictionary) -  contains all the preferences of a supervisor along with their paths in ACM tree.

            quota (int) - is the number of students a supervisor can supervise.
                                     
            realID (string) - is the actual id of the supervisor in university records.
            name (string) -  is the name of the supervisor in university records.
        
        """
        
        self._keywords = keywords
        self._supID = supID
        self._quota = quota
        self._realID = realID
        self._name = name

    def getSupervisorID(self):
        """ Function to get the Supervisor ID (temporary)"""
        
        return self._supID

    def getKeywords(self):
        """Function to get the keywords dictionary"""
        
        return self._keywords

    def getQuota(self):
        """Function to get the Supervisor Quota"""
        
        return self._quota

    def getSupervisorName(self):
        """ Function to the get the Supervisor Name"""
        
        return self._name

    def getRealID(self):
        """Function to get the real Supervisor ID"""
        
        return self._realID

